lsi: false
safe: true
source: https://github.com/Baz333/software-engineering-project
theme: minima
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Software Engineering Project
description: Project page for Software Engineering Practice by Liam Flynn, Daniel Lizura, Radvydas Mikalauskas, and Barry Nolan
