lsi: false
safe: true
source: https://github.com/Baz333/software-engineering-project
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
